// apps/zcode-gpui/scripts/extract_i18n.ts
// Extracts translations from packages/ui/src/i18n/locales/{en-US,zh-CN}.ts into Rust tables.

import { resolve } from "node:path";
import enUS from "../../../packages/ui/src/i18n/locales/en-US.ts";
import zhCN from "../../../packages/ui/src/i18n/locales/zh-CN.ts";

function escapeRustStr(s: string): string {
  return JSON.stringify(s);
}

function generateTable(entries: Record<string, string>, name: string): string {
  const keys = Object.keys(entries).sort();
  const lines: string[] = [];
  lines.push(`pub static ${name}: &[(&str, &str)] = &[`);
  for (const k of keys) {
    const v = entries[k];
    if (typeof v !== "string") {
      throw new Error(`Invalid non-string translation for key '${k}' in ${name}`);
    }
    lines.push(`    (${escapeRustStr(k)}, ${escapeRustStr(v)}),`);
  }
  lines.push(`];`);
  return lines.join("\n");
}

function main() {
  const args = Deno.args;
  const outPath = args[0] || resolve(import.meta.dirname ?? ".", "../src/shared/i18n_data.rs");

  console.log(`Extracting i18n entries (en-US: ${Object.keys(enUS).length}, zh-CN: ${Object.keys(zhCN).length})...`);

  const enTable = generateTable(enUS, "EN_US_TRANSLATIONS");
  const zhTable = generateTable(zhCN, "ZH_CN_TRANSLATIONS");

  const header = `// Auto-generated by extract_i18n.ts. DO NOT EDIT DIRECTLY.\n\n`;
  const content = header + enTable + "\n\n" + zhTable + "\n";

  Deno.writeTextFileSync(outPath, content);
  console.log(`Successfully wrote ${outPath}`);
}

main();
